workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-2
  replicaCount: 1
  containerSpec:
    imageUri: gcr.io/savvy-primacy-426618-p1/mlops_sign_mnist
    env:
    - name: WANDB_API_KEY
      value: $WANDB_API_KEY