steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-sign-mnist-artifact/classifier',
    '-f',
    'train_model.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-sign-mnist-artifact/classifier',
  ]
images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-sign-mnist-artifact/classifier"
options:
  logging: CLOUD_LOGGING_ONLY
