name: "Run tests"

on:
  push:
    branches: 
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip' # caching pip dependencies
      
      - name: Install dependencies
        working-directory: /home/runner/work/mlops_sign_mnist/mlops_sign_mnist/mlops_sign_mnist
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Test with pytest
        working-directory: /home/runner/work/mlops_sign_mnist/mlops_sign_mnist/mlops_sign_mnist
        run: |
          pytest -v
